### ISSUE TITLE
Merge back forked changes

### ISSUE THREAD

**Issue by mrwilson** [mrwilson/byte-monkey#2]
Hi @gluckzhang,

I saw some of the additions you'd made on your fork of `byte-monkey`, and I'd really like to fold them into this codebase.

Would you mind either opening a pull request to merge them in, or if I merged your changes onto here manually?

Thanks,

Alex

**Comment by gluckzhang** [comment]
Hi Alex,
It's great to to know that you are interested in these new features. Acturally I am still working on it and I thought I could contact you later after some optimization. But it's also good to open a pull request now since we can communicate more in a early stage :)
I'll open a PR later today, and look forward to your advice! The main feature is about fault injection within try-catch blocks, which I will introduce more later.

**Comment by mrwilson** [comment]
Closing this, since we merged Short-Circuit mode changes in #3 

Thanks!

**Comment by gluckzhang** [comment]
Hi Alex,
How are you:) In order to have more communication and learn more from industry, I wrote an article to give a brief introduction to my current work. If you are interested in it, that will be great to give me some feedback. It's very valuable if we can collect different suggestions and adjust our research propertly, thanks in advance!
The link is [here](http://blog.gluckzhang.com/archives/158/).
